### ISSUE TITLE
Add list variable type

### ISSUE THREAD

**Issue by vetlek** [equinor/septic-config-generator#200]
Sometimes it is useful to define a list of items for a variable for example wells belonging to a certain flowline that can be iterated through using the standard jinja functionality.

**Comment by einarsi** [comment]
To clarify: In addition to the current datatypes int, float, bool and string (and empty), you want to be able to write some text in a field in a source that should be interpreted as a list?

If I understood that correctly, are the following requirements ok?
- The `[]` construct shall be used to identify lists with comma-separated elements. Example: `[1, 2, 3]`.
- All elements in the list must be of the same type.
- A source file column can only contain one value type. I.e. one row cannot have a list while another has an integer in the same column. The scalar `5` shall therefore be written as `[5]` in "list-columns".

**Comment by einarsi** [comment]
As agreed this has less value after #204 was merged. Closing for now.
