### ISSUE TITLE
option to display TVR as checkbox in DisplayGroup

### ISSUE THREAD

**Issue by AdamZalewski** [equinor/septic-config-generator#51]
As a user I want to be able to display a Bool type TVR tag as a on/off checkbox in the DisplayGroup. 

Background:
The DisplayGroup is able to display EVR of boolean type as a checkbox.  The datatype can be defined by the UserInput=BOOL in the definition of the EVR in DmmyAppl

![image](https://user-images.githubusercontent.com/4906633/223134274-cce65466-bb84-40c5-ae21-d69832255d81.png)

However, when displaying TVR such an option does is not easy to implement as parameter UserInput does not exist for TVR.  Maybe there's another way to specify the data type.

**Comment by einarsi** [comment]
This would need to be implemented in SEPTIC itself, not SCG.
